# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_covered', models.IntegerField()),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField()),
                ('last_stoppage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('contact', models.CharField(max_length=10)),
                ('vehicle_number', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('vehicle_status', models.CharField(choices=[('runnning', 'running'), ('stopped', 'stopped'), ('scheduled', 'scheduled')], max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='journey',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locate.Vehicle'),
        ),
    ]
